import BCPThreshold.AdmissibleBounds
import BCPThreshold.StrictSlackRealization

#print axioms BelgianChocolate.originalWitness_delta_lt_one
#print axioms BelgianChocolate.admissible_lt_one
#print axioms BelgianChocolate.realClosedDiscFactors_rescale
#print axioms BelgianChocolate.strictSlack_realClosedDiscFactors
#print axioms BelgianChocolate.realClosedDiscFactors_originalWitness
#print axioms BelgianChocolate.positiveCertificate_polynomialFeasible
#print axioms BelgianChocolate.strictSlackRealization
